config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :application do
      collection do
        get :comments
      end
    end

    root "application#index"
  end

  devise_for :users

  resources :articles
  resources :articles do
    collection do
      get :get_top_5
    end

    resources :comments
  end

  mount Ckeditor::Engine => '/ckeditor'
  root "articles#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :user_logged_in?
  before_action :set_articles
  before_action :set_comments

  # GET /articles
  def index
    @articles
  end

  # GET /comments
  def comments
    @comments
    #code
  end

  private

  def set_articles
    @articles = Article.where("author_id = ?", "#{current_user.id}")
  end

  def set_comments
    @comments = Comment.where("author_id = ?", "#{current_user.id}")
  end

  def user_logged_in?
    if current_user.nil?
      deny_access
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  #
  before_action :store_current_location

  # if user not logged in
  # store the current location
  # redirect to login form
  def deny_access
    store_current_location

    redirect_to new_user_session_path
  end

  # Ovveride the devise helper to store the current location.
  # We can redirect to it after login
  def store_current_location
    session[:previous_url] = request.fullpath unless request.fullpath =~ /\/users/
  end

  #
  def after_sign_in_path_for(resource)
    session[:previous_url] || root_path
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/application/comments.html.erb
<div class="container">
<div class="page-content">
  <div class="row">
    <div class="col-md-2">
      <div class="sidebar content-box" style="display: block;">
        <ul class="nav">
          <!-- Main menu -->
          <li class="current">
            <a href="/admin">
              <i class="glyphicon glyphicon-book"></i>
              Articles</a>
          </li>
          <li>
            <a href="/admin/application/comments">
              <i class="glyphicon glyphicon-comment"></i>
              Comments</a>
          </li>
        </ul>
      </div>
    </div>

    <div class="col-md-10">
      <div class="row">
        <div class="col-md-12">
          <div class="panel panel-info">
            <div class="panel-heading text-uppercase">Your comments</div>
            <div class="panel-body"></div>
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th>Id</th>
                    <th>Content</th>
                    <th>Comment ON</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  <% @comments.each do |comment| %>
                  <tr>
                    <td><%= comment.id %></td>
                    <td><%= comment.text %></td>
                    <td><%= link_to comment.article.title, comment.article %></td>
                    <td>
                      <%= link_to "", [comment.article, comment], method: :delete,
                                  data: {confirm: "Are you sure you want to delete this comment?"},
                                  class: "glyphicon glyphicon-trash"  %>
                    </td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
<p id="notice" class="hidden"><%= notice %></p>

app/views/admin/application/index.html.erb
<div class="container">
  <div class="page-content">
    <div class="row">
      <div class="col-md-2">
        <div class="sidebar content-box" style="display: block;">
          <ul class="nav">
            <!-- Main menu -->
            <li class="current">
              <a href="/admin">
                <i class="glyphicon glyphicon-book"></i>
                Articles</a>
            </li>
            <li>
              <a href="/admin/application/comments">
                <i class="glyphicon glyphicon-comment"></i>
                Comments</a>
            </li>
          </ul>
        </div>
      </div>

      <div class="col-md-10">
        <div class="row">
          <div class="col-md-12">
            <div class="panel panel-info">
              <div class="panel-heading text-uppercase">The Articles</div>
              <div class="panel-body">
                <%= link_to " New", new_article_path, class: "glyphicon glyphicon-plus" %>
              </div>
              <div class="table-responsive">
                <table class="table">
                  <thead>
                    <tr>
                      <th>Id</th>
                      <th>Title</th>
                      <th>Date created</th>
                      <th>Edit</th>
                      <th>Remove</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @articles.each do |article| %>
                    <tr>
                      <td><%= article.id %></td>
                      <td><%= link_to article.title, article %></td>
                      <td><%= article.created_at.strftime('%b %d, %Y') %></td>
                      <td><%= link_to "", edit_article_path(article), class: "glyphicon glyphicon-edit" %></td>
                      <td>
                        <%= link_to "", article, method: :delete,
                                    data: {confirm: "Are you sure you want to delete this article?"},
                                    class: "glyphicon glyphicon-trash"  %>
                      </td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>
<p id="notice" class="hidden"><%= notice %></p>