config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :application do
      collection do
        get :comments
      end
    end

    root "application#index"
  end

  devise_for :users

  resources :articles
  resources :articles do
    collection do
      get :get_top_5
    end

    resources :comments
  end

  mount Ckeditor::Engine => '/ckeditor'
  root "articles#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="col-md-12 text-center text-muted">
      Copyright [2017] [Designed by Trung]
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<!--NavBar -->
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/articles">Mrlonely</a>
    </div>

    <!-- link -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <a href="/articles">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
      </ul>

      <!-- Nav RIGHT -->
      <ul class="nav navbar-nav navbar-right">
        <!-- Form SEARCH-->
        <form action="<%= articles_path %>" method="get" class="navbar-form navbar-left search-form">
          <%= text_field_tag(:search, params[:search], placeholder: "Search",class: "form-control") %>
          <button type="submit" class="btn btn-default">
            <i class="fa fa-search" aria-hidden="true"></i>
          </button>
        </form>
        <!-- Admin page -->

        <!-- end FOMR -->
      <% unless user_signed_in? %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
      <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello
            <%= current_user.email %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Admin", admin_root_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% end %>
      </ul>
      <!-- end Nav RIGHT -->

    </div>

    <!-- end LINK -->
  </div>
  <!-- navbar collapse -->
</nav>
<!-- NavBar-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog-PreWork</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="/uploads/tmp/blogger.png" rel="shortcut icon" type="image/x-icon">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
      <%= render 'layouts/navbar' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>